### PR TITLE
jenkins_build.sh: No more debug images in non-production builds

### PR DESCRIPTION
**Pull request by agherzan**
Signed-off-by: Andrei Gherzan <andrei@resin.io>

### CODE REVIEW

**Comment by petrosagg** [comment]
Instead of just deleting this can we make it so that it gets its value from an env var that Jenkins provides? And then we'll make Jenkins default to non-debug. This way if someone wants a debug build it will be as simple as starting a jenkins job

**Comment by agherzan** [comment]
Sounds like a good idea. I'll do that.

**Comment by petrosagg** [comment]
SGTM

**Comment by floion** [comment]
LGTM

**Pull request merged**
