### PR TITLE
jenkins_build.sh: Deploy kernel_modules_headers.tar.bz2

### PR DESCRIPTION
**Pull request by floion**
We need this archive exposed as a Jenkins build artifact

Signed-off-by: Florin Sarbu <florin@resin.io>

### CODE REVIEW

**Comment by floion** [comment]
@agherzan @telphan @lorenzo-stoakes @michal-mazurek

**Comment by floion** [comment]
Add to whitelist

**Comment by Page-** [comment]
SGTM

**Comment by lorenzo-stoakes** [comment]
LGTM

**Pull request merged**
