### PR TITLE
automation/jenkins_build.sh: Allow checkout of forked pull requests on the 1.X branch

### PR DESCRIPTION
**Pull request by floion**
When we checkout a meta-resin revision for building we must also take into
consideration that such a revision might be from an external contributor's
fork sent as a pull request.

Signed-off-by: Florin Sarbu <florin@resin.io>

### CODE REVIEW

**Comment by willnewton** [comment]
Are we actually using the 1.X branch? I had been updating the 1.X BSPs to master as the 1.X branch didn't seem to have other required changes to build with current jenkins.

**Comment by floion** [comment]
Yes @willnewton as far as I remember at some point we needed to create a 1.X branch in resin-yocto-scripts specifically for 1.X meta-resin based boards.

**Comment by willnewton** [comment]
As far as I am aware it no longer builds with the current jenkins config and no supported boards are using it.

**Comment by floion** [comment]
@agherzan ^

**Pull request merged**
